name: bitcoin_light_client
description: A bitcoin p2p light client
version: 1.0.0
repository: https://github.com/KolbyML/bitcoin_light_client
issue_tracker: https://github.com/KolbyML/bitcoin_light_client/issues

homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypto: ^2.1.5
  http: ^0.13.0
  test: ^1.16.0
  collection: ^1.15.0
