name: bitcoindart
description: A bitcoin p2p light client
version: 1.0.0
repository: https://github.com/KolbyML/bitcoindart
issue_tracker: https://github.com/KolbyML/bitcoindart/issues

homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypto: ^2.1.5
  http: ^0.13.0
  test: ^1.16.0
